#!/bin/bash

# Usage: ./scripts/build

# Note that bdist_wheel command is used to create Python wheel distributions,
# which are a newer and more efficient format for distributing Python packages
# than the older sdist format you used previously.
# python3.9 setup.py sdist
python3 setup.py bdist_wheel
